service: rust-lambda

privider:
  name: aws
  runtime: provided.al2

package:
  exclude:
    - ./**
  include:
    - ./target/x86_64-unknown-linux-gnu/release/aws_lambda_pizza_api

functions:
  pizza_rust:
    handler: target
    events:
      - http:
          path: /pizza/{pizza_name}/price
          method: GET
          request:
            parameters:
              paths:
                pizza_name: true